### ISSUE TITLE
SCSS compile error

### ISSUE THREAD

**Issue by NLStom** [CodyHouse/cd-team-changelog#1]
When I compile the SCSS, it gives me the following error. 
```

Error: function alpha only takes 1 arguments; given 2
        on line 24 of stdin
>>   background: linear-gradient(alpha(var(--color-black), 0), alpha(var(--color-
   ------------------------------^
```

```
Error: no mixin named fontSmooth
       Backtrace:
       	stdin:29
        on line 29 of stdin
>>   @include fontSmooth;
```

**Comment by sebastiano-guerriero** [comment]
Hi there, have you imported CodyFrame? It appears the _mixins.scss file is missing.

Getting started with CodyFrame:
https://codyhouse.co/ds/get-started

CodyFrame mixins:
https://codyhouse.co/ds/docs/framework/mixins

**Comment by claudia-romano** [comment]
I'm closing this issue as no additional details were provided. Feel free to reopen it if you are still experiencing this bug.

Cheers!
